server:
  port: 8083
spring:
  application:
    name: bangong-server
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: zkz524300@
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
   # registry-fetch-interval-seconds: 15 #默认为30，开发环境中设置小一点，能够快速得到服务的最新状态
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳,生产环境去掉这两个配置
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
###########################thymeleaf配置######################

#######################mabatic配置###########################